## In. this notebook
1. Pull and combine all 2022 arrests data
2. Analyze it for:

    a. arrests in year by state for 2022
    
    b. arrests in NY for 2022
    
    c. arrests in Capital Region for 2022

In [1]:
## import necessary libraries
import pandas as pd

In [3]:
df22 = pd.read_csv('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/CLEANED-ICEarrests-Albany/FilteredData/2022ICEArrestsData.csv', low_memory=False)
df22

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2022-10-05 11:08:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00002880c7d1c7fc09144a3fe22a5b45c5c204a6
1,2022-11-18 11:40:00,NaN,NEW JERSEY,NaN,Newark Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,HAITI,Male,NaN,NaN,ICE ERO NEWARK,-,"NEWARK, NJ, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00012138344f907502a4c08061b6793d9694f390
2,2022-10-20 07:51:00,NaN,INDIANA,NaN,Chicago Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,MEXICO,Male,NaN,NaN,"INP GENERAL AREA, NON-SPECIFIC",-,"ERO - Indianapolis, IN Sub-Office",3 Other Immigration Violator,NaN,0001881592ace06cdaa5af0f8bf065385a6e3491
3,2022-12-14 08:50:00,NaN,NaN,NaN,Denver Area of Responsibility,Mobile Criminal Alien Team,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Male,NaN,NaN,DENVER COUNTY,NaN,"DENVER, CO, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00019fa9e0aa94625220c91d01d1285f5accf081
4,2022-11-03 11:21:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,COLOMBIA,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00037689c6eb841eef84ffa417b8669c914acf78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48624,2022-12-30 10:24:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,9-VR Witnessed,...,MEXICO,Male,2022-12-30 00:00:00,NaN,"SEGOVIA STATE JAIL- PRE-RELEASE, TX",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,3.0,NaN
48625,2022-12-30 12:14:54,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNKNOWN,Female,NaN,NaN,NaN,NaN,"COLUMBUS, NM, POE",NaN,NaN,NaN
48626,2022-12-31 08:29:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2022-12-31 00:00:00,NaN,"SEGOVIA STATE JAIL- PRE-RELEASE, TX",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
48627,2022-12-31 09:04:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP State Incarceration,1 Convicted Criminal,9-VR Witnessed,...,MEXICO,Male,2022-12-31 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,3.0,NaN
48628,2022-12-14 11:00:00,NaN,NaN,NaN,Chicago Area of Responsibility,ERO Criminal Alien Program,ICE,Located,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,"CHI GENERAL AREA, NON-SPECIFIC",NaN,"CHICAGO, IL, DOCKET CONTROL OFFICE",NaN,NaN,NaN

In [4]:
df22_state = df22["State"].value_counts()
df22_state

TEXAS                             8007
NEW JERSEY                        3406
NEW YORK                          2600
CALIFORNIA                        2510
MASSACHUSETTS                     2298
FLORIDA                           1849
TENNESSEE                         1298
COLORADO                          1094
SOUTH CAROLINA                     694
PENNSYLVANIA                       686
NORTH CAROLINA                     667
OHIO                               617
UTAH                               605
OKLAHOMA                           605
WASHINGTON                         579
GEORGIA                            566
VIRGINIA                           554
MARYLAND                           549
LOUISIANA                          534
ILLINOIS                           509
ARIZONA                            474
MAINE                              459
NEBRASKA                           416
ALABAMA                            388
MICHIGAN                           360
MISSISSIPPI                        327
INDIANA                            326
MISSOURI                           248
MINNESOTA                          247
IOWA                               219
KENTUCKY                           208
WISCONSIN                          206
ARKANSAS                           179
KANSAS                             140
NEW HAMPSHIRE                      115
PUERTO RICO                        100
IDAHO                               93
NEVADA                              74
WEST VIRGINIA                       67
RHODE ISLAND                        61
SOUTH DAKOTA                        58
NEW MEXICO                          54
WYOMING                             54
MONTANA                             49
DELAWARE                            42
CONNECTICUT                         34
OREGON                              30
VERMONT                             21
ALASKA                              16
NORTH DAKOTA                        12
HAWAII                               6
DISTRICT OF COLUMBIA                 5
VIRGIN ISLANDS                       3
ARMED FORCES - THE AMERICAS          2
GUAM                                 1
FEDERATED STATES OF MICRONESIA       1
Name: State, dtype: int64

In [5]:
df22_state.to_csv('FilteredData/2022DeportationByState.csv', index=True)

In [6]:
df_NY = df22.query('State == "NEW YORK"') 
df_NY

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2022-10-05 11:08:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00002880c7d1c7fc09144a3fe22a5b45c5c204a6
4,2022-11-03 11:21:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,COLOMBIA,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00037689c6eb841eef84ffa417b8669c914acf78
11,2022-11-28 12:22:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Female,NaN,2023-06-01 00:00:00,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,000ba771d28c60a510e780b1e210bb8fe20d05ae
13,2022-10-26 13:43:00,NaN,NEW YORK,NaN,El Paso Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"ERO - El Paso, TX SPC Sub-Office",3 Other Immigration Violator,NaN,000df835781a3e9d84e3af011371e74dddf11ab2
16,2022-10-12 13:26:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,PERU,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00110c85a51b2d99a9c04735950055fe94e755af
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47807,2022-10-18 12:31:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,A-Proceedings Terminated,...,PERU,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,ff4a898431e87c6ed45e56b72f5cebb00189b8b4
47811,2022-12-14 11:06:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,COLOMBIA,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,ff51a2b5cf958a8fc5ab9db16b549599300daccc
47813,2022-12-05 15:06:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,ff57e44177f09130ea1617aadcbfb3a321f0ae9a
47858,2022-12-12 11:47:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,3-Voluntary Departure Confirmed,...,JAMAICA,Male,2023-03-17 00:00:00,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,ff9bea44e19f1791b1b73b62a7d7b59f8f20df06
48599,2022-12-20 06:15:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,"XBU GENERAL AREA, NON-SPECIFIC",NaN,"BUFFALO, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN

In [7]:
NYcounts = df_NY['Apprehension Site Landmark'].value_counts()
NYcounts

NDD - 26 FEDERAL PLAZA NY, NY                             1859
ERIE COUNTY                                                296
CIP GENERAL AREA, NON-SPECIFIC                             105
WENDE CORRECTIONAL FACILITY                                 78
SARATOGA COUNTY                                             55
ONONDAGA COUNTY                                             31
FUGITIVE OPERATIONS NY STATE                                26
FEDERAL CORRECTIONAL INSTITUTE RAY BROOK                    17
NON-DETAINED AND JUVENILE                                   17
ALBANY COUNTY                                               17
CLINTON COUNTY                                              12
CAP - BOP BROOKLYN NY STATE                                 12
CAP - ORANGE COUNTY JAIL NY STATE                            6
CAP - OTISVILLE FEDERAL CORRECTIONAL FACILITY NY STATE       5
CAP - NASSAU COUNTY JAIL NY STATE                            5
NON-DETAINED and Juvenile                                    4
NBG GENERAL AREA, NON-SPECIFIC                               3
BOP BROOKLYN                                                 3
CAP - SUFFOLK COUNTY JAIL NY STATE                           3
SCHENECTADY COUNTY JAIL                                      2
CAP - NEWBURGH TOWN POLICE DEPARTMENT, NY STATE              2
CAP - USM - SOUTHERN DISTRICT NY STATE                       2
CAP - COUNTY, STATE, LEA REF NY STATE                        2
CAP - ORANGE COUNTY PROBATION  NY STATE                      2
CAP - SPRING VALLEY POLICE DEPARTMENT, NY STATE              2
DO NOT USE                                                   2
CAP - PUTNAM COUNTY JAIL NY STATE                            2
CAP - NEWBURGH CITYPOLICE DEPARTMENT, NY STATE               2
JCART STREET ARREST NY STATE                                 1
MONROE COUNTY JAIL                                           1
ATD NY STATE                                                 1
CAP - DUTCHESS COUNTY SHERIFF NY STATE                       1
CAP - PORT CHESTER VILLAGE POLICE DEPARTMENT NY STATE        1
CAP - MIDDLETOWN CITY POLICE DEPARTMENT, NY STATE            1
ONTARIO COUNTY JAIL                                          1
RENSSELAER COUNTY JAIL                                       1
CAP - MIDDLETOWN POLICE DEPARTMENT NY STATE                  1
CAP - BROOKLYN CENTRAL BOOKING NY State                      1
ALBION CORRECTIONAL FACILITY                                 1
CAP - NASSAU COUNTY JUVENILE DETENTION CENTER NY STATE       1
CAP - DUTCHESS COUNTY JAIL  NY STATE                         1
GREENE COUNTY                                                1
NYC GENERAL AREA, NON-SPECIFIC                               1
CAP - ROCKLAND COUNTY JAIL NY STATE                          1
ONTARIO COUNTY                                               1
COLUMBIA COUNTY                                              1
SYR GENERAL AREA, NON-SPECIFIC                               1
NIAGARA COUNTY JAIL                                          1
ERIE COUNTY JAIL                                             1
MONROE COUNTY                                                1
BUFFALO GENERAL - Do Not Use                                 1
CAP - RAMAPO TOWN POLICE DEPARTMENT, NY STATE                1
CAP - USM - MANHATTAN NY State                               1
CAP - ORANGE COUNTY SHERRIFF, NY STATE                       1
ONEIDA COUNTY JAIL                                           1
XBU GENERAL AREA, NON-SPECIFIC                               1
Name: Apprehension Site Landmark, dtype: int64

In [8]:
NYcounts.to_csv('RawData/2022DeportationByNY.csv', index=True)

In [9]:
df_NY['Apprehension Site Landmark'].unique()

array(['NDD - 26 FEDERAL PLAZA NY, NY', 'ERIE COUNTY', 'SARATOGA COUNTY',
       'FUGITIVE OPERATIONS NY STATE', 'BOP BROOKLYN', 'ONONDAGA COUNTY',
       'ALBANY COUNTY', 'CIP GENERAL AREA, NON-SPECIFIC',
       'FEDERAL CORRECTIONAL INSTITUTE RAY BROOK',
       'WENDE CORRECTIONAL FACILITY', 'CAP - NASSAU COUNTY JAIL NY STATE',
       'CLINTON COUNTY', 'CAP - NEWBURGH CITYPOLICE DEPARTMENT, NY STATE',
       'CAP - BOP BROOKLYN NY STATE',
       'CAP - SUFFOLK COUNTY JAIL NY STATE', 'ONEIDA COUNTY JAIL',
       'CAP - ORANGE COUNTY SHERRIFF, NY STATE',
       'CAP - USM - MANHATTAN NY State', 'NON-DETAINED and Juvenile',
       'CAP - RAMAPO TOWN POLICE DEPARTMENT, NY STATE',
       'NON-DETAINED AND JUVENILE', 'CAP - ORANGE COUNTY JAIL NY STATE',
       'NBG GENERAL AREA, NON-SPECIFIC',
       'CAP - USM - SOUTHERN DISTRICT NY STATE',
       'BUFFALO GENERAL - Do Not Use', 'MONROE COUNTY',
       'ERIE COUNTY JAIL', 'NIAGARA COUNTY JAIL',
       'CAP - DUTCHESS COUNTY JAIL  NY STATE',
       'SYR GENERAL AREA, NON-SPECIFIC',
       'CAP - SPRING VALLEY POLICE DEPARTMENT, NY STATE',
       'COLUMBIA COUNTY',
       'CAP - OTISVILLE FEDERAL CORRECTIONAL FACILITY NY STATE',
       'CAP - NEWBURGH TOWN POLICE DEPARTMENT, NY STATE',
       'CAP - ORANGE COUNTY PROBATION  NY STATE', 'ONTARIO COUNTY',
       'DO NOT USE', 'CAP - PUTNAM COUNTY JAIL NY STATE',
       'CAP - ROCKLAND COUNTY JAIL NY STATE',
       'NYC GENERAL AREA, NON-SPECIFIC', 'GREENE COUNTY',
       'ONTARIO COUNTY JAIL',
       'CAP - NASSAU COUNTY JUVENILE DETENTION CENTER NY STATE',
       'JCART STREET ARREST NY STATE',
       'CAP - COUNTY, STATE, LEA REF NY STATE', 'MONROE COUNTY JAIL',
       'CAP - DUTCHESS COUNTY SHERIFF NY STATE',
       'SCHENECTADY COUNTY JAIL',
       'CAP - PORT CHESTER VILLAGE POLICE DEPARTMENT NY STATE',
       'CAP - MIDDLETOWN CITY POLICE DEPARTMENT, NY STATE',
       'ATD NY STATE', 'RENSSELAER COUNTY JAIL',
       'CAP - MIDDLETOWN POLICE DEPARTMENT NY STATE',
       'CAP - BROOKLYN CENTRAL BOOKING NY State',
       'ALBION CORRECTIONAL FACILITY', 'XBU GENERAL AREA, NON-SPECIFIC'],
      dtype=object)

In [10]:
CapitalRegion= ['ALBANY COUNTY','RENSSELAER COUNTY', 'SARATOGA COUNTY', 'GREENE COUNTY', 'WARREN COUNTY', 'WARREN COUNTY JAIL', 'SCHENECTADY COUNTY JAIL', 'SARATOGA COUNTY JAIL', 'RENSSELAER COUNTY JAIL', 'WASHINGTON CORRECTIONAL FACILITY', 'WASHINGTON COUNTY JAIL']

In [11]:
df_CR = df_NY[df_NY['Apprehension Site Landmark'].isin(CapitalRegion)]

In [12]:
df_CR

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
24,2022-12-14 00:00:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Male,NaN,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,001a179f433d01d413081d78da77f37f4463bcc4
322,2022-10-13 09:30:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,B-Relief Granted,...,NICARAGUA,Male,NaN,NaN,ALBANY COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,018503e674ea57050430c0b42628ac4b2c0023ec
622,2022-10-04 10:28:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,INDIA,Male,NaN,NaN,ALBANY COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,0323cf96d6e03f903cff84271fc30e5e15d62233
982,2022-11-29 11:26:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,B-Relief Granted,...,TURKIYE,Male,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,051d300f12f999cb3acb1917d1a50c518dd8ccc1
2479,2022-12-27 12:49:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,B-Relief Granted,...,ECUADOR,Male,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,0d4ff936d631963d83d68825f2875f579bd1df28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45392,2022-11-29 11:16:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,B-Relief Granted,...,TURKIYE,Female,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,f27a2aedfa82147ad6a8e79bf2cec256e221e73d
45738,2022-10-26 12:47:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Female,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,f42291c0f395485cb111a62bbba90cfbf7e26f86
45766,2022-12-06 09:43:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,COLOMBIA,Male,NaN,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,f44cf069ac4e5b9373277972c3fb6b0ed46798e3
46498,2022-11-02 12:19:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,PAKISTAN,Male,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",NaN,NaN,f8504d862239fb98ede1251e8f8f535220644d09
46934,2022-11-15 11:13:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,BRAZIL,Male,NaN,2025-09-04 00:00:00,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,fabb7527fca1312f5dbe6992cd91860e89924020

In [13]:
df_CR.to_csv('FilteredData/2022CapitalRegionICEArrests.csv', index = True)

In [14]:
df_CR["Apprehension Site Landmark"].value_counts()

SARATOGA COUNTY            55
ALBANY COUNTY              17
SCHENECTADY COUNTY JAIL     2
GREENE COUNTY               1
RENSSELAER COUNTY JAIL      1
Name: Apprehension Site Landmark, dtype: int64